[package]
name = "turnstile_hopper"
version = "0.1.0"
authors = ["jsc <jsc+bones@demigods.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.5.1"
indextree = "4.3.1"
